package com.gdut.myproject.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALARM_RECORD".
 */
public class AlarmRecord {

    private Long id;
    /** Not-null value. */
    private String date_alarm;
    private String type;

    public AlarmRecord() {
    }

    public AlarmRecord(Long id) {
        this.id = id;
    }

    public AlarmRecord(Long id, String date_alarm, String type) {
        this.id = id;
        this.date_alarm = date_alarm;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate_alarm() {
        return date_alarm;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate_alarm(String date_alarm) {
        this.date_alarm = date_alarm;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
