package com.gdut.myproject.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATA".
 */
public class Data {

    private Long id;
    /** Not-null value. */
    private String date;
    private String now;

    public Data() {
    }

    public Data(Long id) {
        this.id = id;
    }

    public Data(Long id, String date, String now) {
        this.id = id;
        this.date = date;
        this.now = now;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public String getNow() {
        return now;
    }

    public void setNow(String now) {
        this.now = now;
    }

}
