package com.gdut.myproject.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAY_DATA".
 */
public class DayData {

    private Long id;
    private String key;
    /** Not-null value. */
    private String day;
    private String daytotal;

    public DayData() {
    }

    public DayData(Long id) {
        this.id = id;
    }

    public DayData(Long id, String key, String day, String daytotal) {
        this.id = id;
        this.key = key;
        this.day = day;
        this.daytotal = daytotal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getDay() {
        return day;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDay(String day) {
        this.day = day;
    }

    public String getDaytotal() {
        return daytotal;
    }

    public void setDaytotal(String daytotal) {
        this.daytotal = daytotal;
    }

}
