package com.gdut.myproject.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INSTANT_DATA".
 */
public class InstantData {

    private Long id;
    /** Not-null value. */
    private String time;
    private String instantvalue;

    public InstantData() {
    }

    public InstantData(Long id) {
        this.id = id;
    }

    public InstantData(Long id, String time, String instantvalue) {
        this.id = id;
        this.time = time;
        this.instantvalue = instantvalue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public String getInstantvalue() {
        return instantvalue;
    }

    public void setInstantvalue(String instantvalue) {
        this.instantvalue = instantvalue;
    }

}
